#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo '\n==========Testing================='
make test
echo '\n==========Linter=================='
make check
echo '\n==========Build==================='
make build
echo '\n==========Cleaning build=========='
make clean
echo '\n==========Finished================\n'